# Generated by Django 5.2 on 2025-04-10 15:53

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('fileupload', models.FileField(upload_to='resources/', validators=[base.models.validate_file_type_and_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
