# Generated by Django 5.2 on 2025-04-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_postresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postresource',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='postresource',
            name='fileupload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='postresource',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
