# Generated by Django 5.2 on 2025-04-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_postresource_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postresource',
            name='fileupload',
        ),
    ]
