# Generated by Django 5.2 on 2025-04-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_documentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='fileupload',
            field=models.FileField(blank=True, null=True, upload_to='resource/'),
        ),
        migrations.AddField(
            model_name='postresource',
            name='fileupload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
