# Generated by Django 5.2 on 2025-04-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_upcomingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
