# Generated by Django 5.2 on 2025-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_upcomingevent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevent',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='event/'),
        ),
    ]
